apiVersion: 1

datasources:
  - name: InfluxDB ($PROJECT_NAME)
    type: influxdb
    access: proxy
    database: $DOCKER_INFLUXDB_INIT_USERNAME
    url: http://influxdb:8086
    user: $DOCKER_INFLUXDB_INIT_USERNAME
    secureJsonData:
      password: $DOCKER_INFLUXDB_INIT_PASSWORD
    isDefault: true
    editable: true